### ISSUE TITLE
[Error] F2613: Unit 'PngFunctions' not found when compiling Cod.SysUtils.pas

### ISSUE THREAD

**Issue by lovehyunju** [Codrax/Cod-Windows-Runtime#1]
### Title  
`[Error] F2613: Unit 'PngFunctions' not found when compiling Cod.SysUtils.pas`

### Content  
Hello,  

I encountered the following error while building the project:  
```
[dcc32 Fatal Error] Cod.SysUtils.pas(21): F2613 Unit 'PngFunctions' not found.
```

The error occurs on line 21 of the `Cod.SysUtils.pas` file, indicating that the `PngFunctions` unit cannot be found. Could you confirm if this file is missing or if it is part of an external dependency that needs to be installed separately?  

Thank you!

**Comment by Codrax** [comment]
Hi there!

My mistake. I've completely forgotten about that unit, I believe It used to be included in older versions of Delphi. It's part of the PNGTools library.

I will include It in the repository as soon as I can, or just remove It.

Thank you for pointing this out to me!

**Comment by Codrax** [comment]
I've bundled the required functions from `PNGFunctions` into the allready existing units of mine. Your app should now compile.

Have a nice day! :)
